package cn.nhsoft.amazoncloud.apitest.dao.ama5.model;

import java.math.BigDecimal;
import java.util.Date;

public class PosItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_num
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private Integer itemNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.system_book_code
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private String systemBookCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_code
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private String itemCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_barcode
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private String itemBarcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_name
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private String itemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_spec
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private String itemSpec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.store_item_pinyin
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private String storeItemPinyin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_type
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private Integer itemType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_unit
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private String itemUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_department
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private String itemDepartment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_category
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private String itemCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_regular_price
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private BigDecimal itemRegularPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_level2_price
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private BigDecimal itemLevel2Price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_level3_price
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private BigDecimal itemLevel3Price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_level4_price
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private BigDecimal itemLevel4Price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_note_info
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private String itemNoteInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_sale_message
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private String itemSaleMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_invoice_message
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private String itemInvoiceMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.store_item_flag
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private Byte storeItemFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.store_item_matrix_property
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private String storeItemMatrixProperty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.store_item_pack
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private BigDecimal storeItemPack;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_pos_change_price_flag
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private Byte itemPosChangePriceFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_min_price
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private BigDecimal itemMinPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_del_tag
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private Byte itemDelTag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_point_actived
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private Byte itemPointActived;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_point_value
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private BigDecimal itemPointValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_brand
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private String itemBrand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_cost_mode
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private String itemCostMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_valid_period
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private Integer itemValidPeriod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_remind_period
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private Integer itemRemindPeriod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_stock_cease_flag
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private Byte itemStockCeaseFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_sale_cease_flag
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private Byte itemSaleCeaseFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_purchase_scope
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private String itemPurchaseScope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_cost_price
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private BigDecimal itemCostPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_transfer_price
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private BigDecimal itemTransferPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_category_code
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private String itemCategoryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_assist_unit
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private String itemAssistUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_place
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private String itemPlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_sequence
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private Integer itemSequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_create_time
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private Date itemCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_eliminative_flag
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private Byte itemEliminativeFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_weight_flag
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private Byte itemWeightFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.ITEM_STORE_PLACE
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private String itemStorePlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_assist_rate
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private BigDecimal itemAssistRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_purchase_unit
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private String itemPurchaseUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_purchase_rate
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private BigDecimal itemPurchaseRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_inventory_unit
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private String itemInventoryUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_inventory_rate
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private BigDecimal itemInventoryRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_transfer_unit
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private String itemTransferUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_transfer_rate
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private BigDecimal itemTransferRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_wholesale_unit
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private String itemWholesaleUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_wholesale_rate
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private BigDecimal itemWholesaleRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_unit_group
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private String itemUnitGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.ITEM_WHOLESALE_PRICE
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private BigDecimal itemWholesalePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.ITEM_PRICE_TAG_FLAG
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private Byte itemPriceTagFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.ITEM_DEL_TIME
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private Date itemDelTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.ITEM_LAST_EDIT_TIME
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private Date itemLastEditTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.ITEM_GROSS_RATE
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private BigDecimal itemGrossRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.ITEM_METHOD
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private String itemMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_status
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private Integer itemStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_level2_wholesale
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private BigDecimal itemLevel2Wholesale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_level3_wholesale
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private BigDecimal itemLevel3Wholesale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_level4_wholesale
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private BigDecimal itemLevel4Wholesale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.ITEM_EN_NAME
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private String itemEnName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_synch_flag
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private Byte itemSynchFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_wholesale_flag
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private Byte itemWholesaleFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.store_item_in_tax
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private BigDecimal storeItemInTax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.store_item_out_tax
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private BigDecimal storeItemOutTax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_barcode_two
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private String itemBarcodeTwo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_barcode_three
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private String itemBarcodeThree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_transfer_gross
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private BigDecimal itemTransferGross;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_transfer_fixed_gross
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private Byte itemTransferFixedGross;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_wholesale_gross
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private BigDecimal itemWholesaleGross;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_wholesale_fixed_gross
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private Byte itemWholesaleFixedGross;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_discounted
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private Byte itemDiscounted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_print_label_flag
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private Byte itemPrintLabelFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_min_quantity
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private BigDecimal itemMinQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_wholesale_gross2
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private BigDecimal itemWholesaleGross2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_wholesale_fixed_gross2
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private Byte itemWholesaleFixedGross2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_wholesale_gross3
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private BigDecimal itemWholesaleGross3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_wholesale_fixed_gross3
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private Byte itemWholesaleFixedGross3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_wholesale_gross4
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private BigDecimal itemWholesaleGross4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_wholesale_fixed_gross4
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private Byte itemWholesaleFixedGross4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_max_price
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private BigDecimal itemMaxPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_transfer_day
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private Integer itemTransferDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_in_tax
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private BigDecimal itemInTax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_out_tax
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private BigDecimal itemOutTax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_manufacture_flag
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private Byte itemManufactureFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_finished_rate
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private BigDecimal itemFinishedRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_extend1
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private String itemExtend1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_extend2
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private String itemExtend2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_extend3
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private String itemExtend3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_has_matrix
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private Byte itemHasMatrix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_creator
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private String itemCreator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_transfer_fix_type
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private Integer itemTransferFixType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.item_wholesale_fix_type
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private Integer itemWholesaleFixType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.branch_num
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private Integer branchNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_item.aged_timestamp
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    private Date agedTimestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_num
     *
     * @return the value of pos_item.item_num
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public Integer getItemNum() {
        return itemNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_num
     *
     * @param itemNum the value for pos_item.item_num
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemNum(Integer itemNum) {
        this.itemNum = itemNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.system_book_code
     *
     * @return the value of pos_item.system_book_code
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public String getSystemBookCode() {
        return systemBookCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.system_book_code
     *
     * @param systemBookCode the value for pos_item.system_book_code
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setSystemBookCode(String systemBookCode) {
        this.systemBookCode = systemBookCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_code
     *
     * @return the value of pos_item.item_code
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public String getItemCode() {
        return itemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_code
     *
     * @param itemCode the value for pos_item.item_code
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_barcode
     *
     * @return the value of pos_item.item_barcode
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public String getItemBarcode() {
        return itemBarcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_barcode
     *
     * @param itemBarcode the value for pos_item.item_barcode
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemBarcode(String itemBarcode) {
        this.itemBarcode = itemBarcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_name
     *
     * @return the value of pos_item.item_name
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_name
     *
     * @param itemName the value for pos_item.item_name
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_spec
     *
     * @return the value of pos_item.item_spec
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public String getItemSpec() {
        return itemSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_spec
     *
     * @param itemSpec the value for pos_item.item_spec
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemSpec(String itemSpec) {
        this.itemSpec = itemSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.store_item_pinyin
     *
     * @return the value of pos_item.store_item_pinyin
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public String getStoreItemPinyin() {
        return storeItemPinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.store_item_pinyin
     *
     * @param storeItemPinyin the value for pos_item.store_item_pinyin
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setStoreItemPinyin(String storeItemPinyin) {
        this.storeItemPinyin = storeItemPinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_type
     *
     * @return the value of pos_item.item_type
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public Integer getItemType() {
        return itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_type
     *
     * @param itemType the value for pos_item.item_type
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemType(Integer itemType) {
        this.itemType = itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_unit
     *
     * @return the value of pos_item.item_unit
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public String getItemUnit() {
        return itemUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_unit
     *
     * @param itemUnit the value for pos_item.item_unit
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemUnit(String itemUnit) {
        this.itemUnit = itemUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_department
     *
     * @return the value of pos_item.item_department
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public String getItemDepartment() {
        return itemDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_department
     *
     * @param itemDepartment the value for pos_item.item_department
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemDepartment(String itemDepartment) {
        this.itemDepartment = itemDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_category
     *
     * @return the value of pos_item.item_category
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public String getItemCategory() {
        return itemCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_category
     *
     * @param itemCategory the value for pos_item.item_category
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemCategory(String itemCategory) {
        this.itemCategory = itemCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_regular_price
     *
     * @return the value of pos_item.item_regular_price
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public BigDecimal getItemRegularPrice() {
        return itemRegularPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_regular_price
     *
     * @param itemRegularPrice the value for pos_item.item_regular_price
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemRegularPrice(BigDecimal itemRegularPrice) {
        this.itemRegularPrice = itemRegularPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_level2_price
     *
     * @return the value of pos_item.item_level2_price
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public BigDecimal getItemLevel2Price() {
        return itemLevel2Price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_level2_price
     *
     * @param itemLevel2Price the value for pos_item.item_level2_price
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemLevel2Price(BigDecimal itemLevel2Price) {
        this.itemLevel2Price = itemLevel2Price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_level3_price
     *
     * @return the value of pos_item.item_level3_price
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public BigDecimal getItemLevel3Price() {
        return itemLevel3Price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_level3_price
     *
     * @param itemLevel3Price the value for pos_item.item_level3_price
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemLevel3Price(BigDecimal itemLevel3Price) {
        this.itemLevel3Price = itemLevel3Price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_level4_price
     *
     * @return the value of pos_item.item_level4_price
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public BigDecimal getItemLevel4Price() {
        return itemLevel4Price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_level4_price
     *
     * @param itemLevel4Price the value for pos_item.item_level4_price
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemLevel4Price(BigDecimal itemLevel4Price) {
        this.itemLevel4Price = itemLevel4Price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_note_info
     *
     * @return the value of pos_item.item_note_info
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public String getItemNoteInfo() {
        return itemNoteInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_note_info
     *
     * @param itemNoteInfo the value for pos_item.item_note_info
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemNoteInfo(String itemNoteInfo) {
        this.itemNoteInfo = itemNoteInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_sale_message
     *
     * @return the value of pos_item.item_sale_message
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public String getItemSaleMessage() {
        return itemSaleMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_sale_message
     *
     * @param itemSaleMessage the value for pos_item.item_sale_message
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemSaleMessage(String itemSaleMessage) {
        this.itemSaleMessage = itemSaleMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_invoice_message
     *
     * @return the value of pos_item.item_invoice_message
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public String getItemInvoiceMessage() {
        return itemInvoiceMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_invoice_message
     *
     * @param itemInvoiceMessage the value for pos_item.item_invoice_message
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemInvoiceMessage(String itemInvoiceMessage) {
        this.itemInvoiceMessage = itemInvoiceMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.store_item_flag
     *
     * @return the value of pos_item.store_item_flag
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public Byte getStoreItemFlag() {
        return storeItemFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.store_item_flag
     *
     * @param storeItemFlag the value for pos_item.store_item_flag
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setStoreItemFlag(Byte storeItemFlag) {
        this.storeItemFlag = storeItemFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.store_item_matrix_property
     *
     * @return the value of pos_item.store_item_matrix_property
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public String getStoreItemMatrixProperty() {
        return storeItemMatrixProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.store_item_matrix_property
     *
     * @param storeItemMatrixProperty the value for pos_item.store_item_matrix_property
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setStoreItemMatrixProperty(String storeItemMatrixProperty) {
        this.storeItemMatrixProperty = storeItemMatrixProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.store_item_pack
     *
     * @return the value of pos_item.store_item_pack
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public BigDecimal getStoreItemPack() {
        return storeItemPack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.store_item_pack
     *
     * @param storeItemPack the value for pos_item.store_item_pack
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setStoreItemPack(BigDecimal storeItemPack) {
        this.storeItemPack = storeItemPack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_pos_change_price_flag
     *
     * @return the value of pos_item.item_pos_change_price_flag
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public Byte getItemPosChangePriceFlag() {
        return itemPosChangePriceFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_pos_change_price_flag
     *
     * @param itemPosChangePriceFlag the value for pos_item.item_pos_change_price_flag
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemPosChangePriceFlag(Byte itemPosChangePriceFlag) {
        this.itemPosChangePriceFlag = itemPosChangePriceFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_min_price
     *
     * @return the value of pos_item.item_min_price
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public BigDecimal getItemMinPrice() {
        return itemMinPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_min_price
     *
     * @param itemMinPrice the value for pos_item.item_min_price
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemMinPrice(BigDecimal itemMinPrice) {
        this.itemMinPrice = itemMinPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_del_tag
     *
     * @return the value of pos_item.item_del_tag
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public Byte getItemDelTag() {
        return itemDelTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_del_tag
     *
     * @param itemDelTag the value for pos_item.item_del_tag
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemDelTag(Byte itemDelTag) {
        this.itemDelTag = itemDelTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_point_actived
     *
     * @return the value of pos_item.item_point_actived
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public Byte getItemPointActived() {
        return itemPointActived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_point_actived
     *
     * @param itemPointActived the value for pos_item.item_point_actived
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemPointActived(Byte itemPointActived) {
        this.itemPointActived = itemPointActived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_point_value
     *
     * @return the value of pos_item.item_point_value
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public BigDecimal getItemPointValue() {
        return itemPointValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_point_value
     *
     * @param itemPointValue the value for pos_item.item_point_value
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemPointValue(BigDecimal itemPointValue) {
        this.itemPointValue = itemPointValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_brand
     *
     * @return the value of pos_item.item_brand
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public String getItemBrand() {
        return itemBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_brand
     *
     * @param itemBrand the value for pos_item.item_brand
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemBrand(String itemBrand) {
        this.itemBrand = itemBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_cost_mode
     *
     * @return the value of pos_item.item_cost_mode
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public String getItemCostMode() {
        return itemCostMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_cost_mode
     *
     * @param itemCostMode the value for pos_item.item_cost_mode
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemCostMode(String itemCostMode) {
        this.itemCostMode = itemCostMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_valid_period
     *
     * @return the value of pos_item.item_valid_period
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public Integer getItemValidPeriod() {
        return itemValidPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_valid_period
     *
     * @param itemValidPeriod the value for pos_item.item_valid_period
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemValidPeriod(Integer itemValidPeriod) {
        this.itemValidPeriod = itemValidPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_remind_period
     *
     * @return the value of pos_item.item_remind_period
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public Integer getItemRemindPeriod() {
        return itemRemindPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_remind_period
     *
     * @param itemRemindPeriod the value for pos_item.item_remind_period
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemRemindPeriod(Integer itemRemindPeriod) {
        this.itemRemindPeriod = itemRemindPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_stock_cease_flag
     *
     * @return the value of pos_item.item_stock_cease_flag
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public Byte getItemStockCeaseFlag() {
        return itemStockCeaseFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_stock_cease_flag
     *
     * @param itemStockCeaseFlag the value for pos_item.item_stock_cease_flag
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemStockCeaseFlag(Byte itemStockCeaseFlag) {
        this.itemStockCeaseFlag = itemStockCeaseFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_sale_cease_flag
     *
     * @return the value of pos_item.item_sale_cease_flag
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public Byte getItemSaleCeaseFlag() {
        return itemSaleCeaseFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_sale_cease_flag
     *
     * @param itemSaleCeaseFlag the value for pos_item.item_sale_cease_flag
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemSaleCeaseFlag(Byte itemSaleCeaseFlag) {
        this.itemSaleCeaseFlag = itemSaleCeaseFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_purchase_scope
     *
     * @return the value of pos_item.item_purchase_scope
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public String getItemPurchaseScope() {
        return itemPurchaseScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_purchase_scope
     *
     * @param itemPurchaseScope the value for pos_item.item_purchase_scope
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemPurchaseScope(String itemPurchaseScope) {
        this.itemPurchaseScope = itemPurchaseScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_cost_price
     *
     * @return the value of pos_item.item_cost_price
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public BigDecimal getItemCostPrice() {
        return itemCostPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_cost_price
     *
     * @param itemCostPrice the value for pos_item.item_cost_price
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemCostPrice(BigDecimal itemCostPrice) {
        this.itemCostPrice = itemCostPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_transfer_price
     *
     * @return the value of pos_item.item_transfer_price
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public BigDecimal getItemTransferPrice() {
        return itemTransferPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_transfer_price
     *
     * @param itemTransferPrice the value for pos_item.item_transfer_price
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemTransferPrice(BigDecimal itemTransferPrice) {
        this.itemTransferPrice = itemTransferPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_category_code
     *
     * @return the value of pos_item.item_category_code
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public String getItemCategoryCode() {
        return itemCategoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_category_code
     *
     * @param itemCategoryCode the value for pos_item.item_category_code
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemCategoryCode(String itemCategoryCode) {
        this.itemCategoryCode = itemCategoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_assist_unit
     *
     * @return the value of pos_item.item_assist_unit
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public String getItemAssistUnit() {
        return itemAssistUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_assist_unit
     *
     * @param itemAssistUnit the value for pos_item.item_assist_unit
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemAssistUnit(String itemAssistUnit) {
        this.itemAssistUnit = itemAssistUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_place
     *
     * @return the value of pos_item.item_place
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public String getItemPlace() {
        return itemPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_place
     *
     * @param itemPlace the value for pos_item.item_place
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemPlace(String itemPlace) {
        this.itemPlace = itemPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_sequence
     *
     * @return the value of pos_item.item_sequence
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public Integer getItemSequence() {
        return itemSequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_sequence
     *
     * @param itemSequence the value for pos_item.item_sequence
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemSequence(Integer itemSequence) {
        this.itemSequence = itemSequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_create_time
     *
     * @return the value of pos_item.item_create_time
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public Date getItemCreateTime() {
        return itemCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_create_time
     *
     * @param itemCreateTime the value for pos_item.item_create_time
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemCreateTime(Date itemCreateTime) {
        this.itemCreateTime = itemCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_eliminative_flag
     *
     * @return the value of pos_item.item_eliminative_flag
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public Byte getItemEliminativeFlag() {
        return itemEliminativeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_eliminative_flag
     *
     * @param itemEliminativeFlag the value for pos_item.item_eliminative_flag
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemEliminativeFlag(Byte itemEliminativeFlag) {
        this.itemEliminativeFlag = itemEliminativeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_weight_flag
     *
     * @return the value of pos_item.item_weight_flag
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public Byte getItemWeightFlag() {
        return itemWeightFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_weight_flag
     *
     * @param itemWeightFlag the value for pos_item.item_weight_flag
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemWeightFlag(Byte itemWeightFlag) {
        this.itemWeightFlag = itemWeightFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.ITEM_STORE_PLACE
     *
     * @return the value of pos_item.ITEM_STORE_PLACE
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public String getItemStorePlace() {
        return itemStorePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.ITEM_STORE_PLACE
     *
     * @param itemStorePlace the value for pos_item.ITEM_STORE_PLACE
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemStorePlace(String itemStorePlace) {
        this.itemStorePlace = itemStorePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_assist_rate
     *
     * @return the value of pos_item.item_assist_rate
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public BigDecimal getItemAssistRate() {
        return itemAssistRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_assist_rate
     *
     * @param itemAssistRate the value for pos_item.item_assist_rate
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemAssistRate(BigDecimal itemAssistRate) {
        this.itemAssistRate = itemAssistRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_purchase_unit
     *
     * @return the value of pos_item.item_purchase_unit
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public String getItemPurchaseUnit() {
        return itemPurchaseUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_purchase_unit
     *
     * @param itemPurchaseUnit the value for pos_item.item_purchase_unit
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemPurchaseUnit(String itemPurchaseUnit) {
        this.itemPurchaseUnit = itemPurchaseUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_purchase_rate
     *
     * @return the value of pos_item.item_purchase_rate
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public BigDecimal getItemPurchaseRate() {
        return itemPurchaseRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_purchase_rate
     *
     * @param itemPurchaseRate the value for pos_item.item_purchase_rate
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemPurchaseRate(BigDecimal itemPurchaseRate) {
        this.itemPurchaseRate = itemPurchaseRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_inventory_unit
     *
     * @return the value of pos_item.item_inventory_unit
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public String getItemInventoryUnit() {
        return itemInventoryUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_inventory_unit
     *
     * @param itemInventoryUnit the value for pos_item.item_inventory_unit
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemInventoryUnit(String itemInventoryUnit) {
        this.itemInventoryUnit = itemInventoryUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_inventory_rate
     *
     * @return the value of pos_item.item_inventory_rate
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public BigDecimal getItemInventoryRate() {
        return itemInventoryRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_inventory_rate
     *
     * @param itemInventoryRate the value for pos_item.item_inventory_rate
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemInventoryRate(BigDecimal itemInventoryRate) {
        this.itemInventoryRate = itemInventoryRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_transfer_unit
     *
     * @return the value of pos_item.item_transfer_unit
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public String getItemTransferUnit() {
        return itemTransferUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_transfer_unit
     *
     * @param itemTransferUnit the value for pos_item.item_transfer_unit
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemTransferUnit(String itemTransferUnit) {
        this.itemTransferUnit = itemTransferUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_transfer_rate
     *
     * @return the value of pos_item.item_transfer_rate
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public BigDecimal getItemTransferRate() {
        return itemTransferRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_transfer_rate
     *
     * @param itemTransferRate the value for pos_item.item_transfer_rate
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemTransferRate(BigDecimal itemTransferRate) {
        this.itemTransferRate = itemTransferRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_wholesale_unit
     *
     * @return the value of pos_item.item_wholesale_unit
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public String getItemWholesaleUnit() {
        return itemWholesaleUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_wholesale_unit
     *
     * @param itemWholesaleUnit the value for pos_item.item_wholesale_unit
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemWholesaleUnit(String itemWholesaleUnit) {
        this.itemWholesaleUnit = itemWholesaleUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_wholesale_rate
     *
     * @return the value of pos_item.item_wholesale_rate
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public BigDecimal getItemWholesaleRate() {
        return itemWholesaleRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_wholesale_rate
     *
     * @param itemWholesaleRate the value for pos_item.item_wholesale_rate
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemWholesaleRate(BigDecimal itemWholesaleRate) {
        this.itemWholesaleRate = itemWholesaleRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_unit_group
     *
     * @return the value of pos_item.item_unit_group
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public String getItemUnitGroup() {
        return itemUnitGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_unit_group
     *
     * @param itemUnitGroup the value for pos_item.item_unit_group
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemUnitGroup(String itemUnitGroup) {
        this.itemUnitGroup = itemUnitGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.ITEM_WHOLESALE_PRICE
     *
     * @return the value of pos_item.ITEM_WHOLESALE_PRICE
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public BigDecimal getItemWholesalePrice() {
        return itemWholesalePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.ITEM_WHOLESALE_PRICE
     *
     * @param itemWholesalePrice the value for pos_item.ITEM_WHOLESALE_PRICE
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemWholesalePrice(BigDecimal itemWholesalePrice) {
        this.itemWholesalePrice = itemWholesalePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.ITEM_PRICE_TAG_FLAG
     *
     * @return the value of pos_item.ITEM_PRICE_TAG_FLAG
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public Byte getItemPriceTagFlag() {
        return itemPriceTagFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.ITEM_PRICE_TAG_FLAG
     *
     * @param itemPriceTagFlag the value for pos_item.ITEM_PRICE_TAG_FLAG
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemPriceTagFlag(Byte itemPriceTagFlag) {
        this.itemPriceTagFlag = itemPriceTagFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.ITEM_DEL_TIME
     *
     * @return the value of pos_item.ITEM_DEL_TIME
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public Date getItemDelTime() {
        return itemDelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.ITEM_DEL_TIME
     *
     * @param itemDelTime the value for pos_item.ITEM_DEL_TIME
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemDelTime(Date itemDelTime) {
        this.itemDelTime = itemDelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.ITEM_LAST_EDIT_TIME
     *
     * @return the value of pos_item.ITEM_LAST_EDIT_TIME
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public Date getItemLastEditTime() {
        return itemLastEditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.ITEM_LAST_EDIT_TIME
     *
     * @param itemLastEditTime the value for pos_item.ITEM_LAST_EDIT_TIME
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemLastEditTime(Date itemLastEditTime) {
        this.itemLastEditTime = itemLastEditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.ITEM_GROSS_RATE
     *
     * @return the value of pos_item.ITEM_GROSS_RATE
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public BigDecimal getItemGrossRate() {
        return itemGrossRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.ITEM_GROSS_RATE
     *
     * @param itemGrossRate the value for pos_item.ITEM_GROSS_RATE
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemGrossRate(BigDecimal itemGrossRate) {
        this.itemGrossRate = itemGrossRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.ITEM_METHOD
     *
     * @return the value of pos_item.ITEM_METHOD
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public String getItemMethod() {
        return itemMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.ITEM_METHOD
     *
     * @param itemMethod the value for pos_item.ITEM_METHOD
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemMethod(String itemMethod) {
        this.itemMethod = itemMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_status
     *
     * @return the value of pos_item.item_status
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public Integer getItemStatus() {
        return itemStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_status
     *
     * @param itemStatus the value for pos_item.item_status
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemStatus(Integer itemStatus) {
        this.itemStatus = itemStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_level2_wholesale
     *
     * @return the value of pos_item.item_level2_wholesale
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public BigDecimal getItemLevel2Wholesale() {
        return itemLevel2Wholesale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_level2_wholesale
     *
     * @param itemLevel2Wholesale the value for pos_item.item_level2_wholesale
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemLevel2Wholesale(BigDecimal itemLevel2Wholesale) {
        this.itemLevel2Wholesale = itemLevel2Wholesale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_level3_wholesale
     *
     * @return the value of pos_item.item_level3_wholesale
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public BigDecimal getItemLevel3Wholesale() {
        return itemLevel3Wholesale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_level3_wholesale
     *
     * @param itemLevel3Wholesale the value for pos_item.item_level3_wholesale
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemLevel3Wholesale(BigDecimal itemLevel3Wholesale) {
        this.itemLevel3Wholesale = itemLevel3Wholesale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_level4_wholesale
     *
     * @return the value of pos_item.item_level4_wholesale
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public BigDecimal getItemLevel4Wholesale() {
        return itemLevel4Wholesale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_level4_wholesale
     *
     * @param itemLevel4Wholesale the value for pos_item.item_level4_wholesale
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemLevel4Wholesale(BigDecimal itemLevel4Wholesale) {
        this.itemLevel4Wholesale = itemLevel4Wholesale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.ITEM_EN_NAME
     *
     * @return the value of pos_item.ITEM_EN_NAME
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public String getItemEnName() {
        return itemEnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.ITEM_EN_NAME
     *
     * @param itemEnName the value for pos_item.ITEM_EN_NAME
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemEnName(String itemEnName) {
        this.itemEnName = itemEnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_synch_flag
     *
     * @return the value of pos_item.item_synch_flag
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public Byte getItemSynchFlag() {
        return itemSynchFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_synch_flag
     *
     * @param itemSynchFlag the value for pos_item.item_synch_flag
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemSynchFlag(Byte itemSynchFlag) {
        this.itemSynchFlag = itemSynchFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_wholesale_flag
     *
     * @return the value of pos_item.item_wholesale_flag
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public Byte getItemWholesaleFlag() {
        return itemWholesaleFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_wholesale_flag
     *
     * @param itemWholesaleFlag the value for pos_item.item_wholesale_flag
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemWholesaleFlag(Byte itemWholesaleFlag) {
        this.itemWholesaleFlag = itemWholesaleFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.store_item_in_tax
     *
     * @return the value of pos_item.store_item_in_tax
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public BigDecimal getStoreItemInTax() {
        return storeItemInTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.store_item_in_tax
     *
     * @param storeItemInTax the value for pos_item.store_item_in_tax
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setStoreItemInTax(BigDecimal storeItemInTax) {
        this.storeItemInTax = storeItemInTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.store_item_out_tax
     *
     * @return the value of pos_item.store_item_out_tax
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public BigDecimal getStoreItemOutTax() {
        return storeItemOutTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.store_item_out_tax
     *
     * @param storeItemOutTax the value for pos_item.store_item_out_tax
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setStoreItemOutTax(BigDecimal storeItemOutTax) {
        this.storeItemOutTax = storeItemOutTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_barcode_two
     *
     * @return the value of pos_item.item_barcode_two
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public String getItemBarcodeTwo() {
        return itemBarcodeTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_barcode_two
     *
     * @param itemBarcodeTwo the value for pos_item.item_barcode_two
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemBarcodeTwo(String itemBarcodeTwo) {
        this.itemBarcodeTwo = itemBarcodeTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_barcode_three
     *
     * @return the value of pos_item.item_barcode_three
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public String getItemBarcodeThree() {
        return itemBarcodeThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_barcode_three
     *
     * @param itemBarcodeThree the value for pos_item.item_barcode_three
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemBarcodeThree(String itemBarcodeThree) {
        this.itemBarcodeThree = itemBarcodeThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_transfer_gross
     *
     * @return the value of pos_item.item_transfer_gross
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public BigDecimal getItemTransferGross() {
        return itemTransferGross;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_transfer_gross
     *
     * @param itemTransferGross the value for pos_item.item_transfer_gross
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemTransferGross(BigDecimal itemTransferGross) {
        this.itemTransferGross = itemTransferGross;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_transfer_fixed_gross
     *
     * @return the value of pos_item.item_transfer_fixed_gross
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public Byte getItemTransferFixedGross() {
        return itemTransferFixedGross;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_transfer_fixed_gross
     *
     * @param itemTransferFixedGross the value for pos_item.item_transfer_fixed_gross
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemTransferFixedGross(Byte itemTransferFixedGross) {
        this.itemTransferFixedGross = itemTransferFixedGross;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_wholesale_gross
     *
     * @return the value of pos_item.item_wholesale_gross
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public BigDecimal getItemWholesaleGross() {
        return itemWholesaleGross;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_wholesale_gross
     *
     * @param itemWholesaleGross the value for pos_item.item_wholesale_gross
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemWholesaleGross(BigDecimal itemWholesaleGross) {
        this.itemWholesaleGross = itemWholesaleGross;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_wholesale_fixed_gross
     *
     * @return the value of pos_item.item_wholesale_fixed_gross
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public Byte getItemWholesaleFixedGross() {
        return itemWholesaleFixedGross;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_wholesale_fixed_gross
     *
     * @param itemWholesaleFixedGross the value for pos_item.item_wholesale_fixed_gross
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemWholesaleFixedGross(Byte itemWholesaleFixedGross) {
        this.itemWholesaleFixedGross = itemWholesaleFixedGross;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_discounted
     *
     * @return the value of pos_item.item_discounted
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public Byte getItemDiscounted() {
        return itemDiscounted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_discounted
     *
     * @param itemDiscounted the value for pos_item.item_discounted
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemDiscounted(Byte itemDiscounted) {
        this.itemDiscounted = itemDiscounted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_print_label_flag
     *
     * @return the value of pos_item.item_print_label_flag
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public Byte getItemPrintLabelFlag() {
        return itemPrintLabelFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_print_label_flag
     *
     * @param itemPrintLabelFlag the value for pos_item.item_print_label_flag
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemPrintLabelFlag(Byte itemPrintLabelFlag) {
        this.itemPrintLabelFlag = itemPrintLabelFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_min_quantity
     *
     * @return the value of pos_item.item_min_quantity
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public BigDecimal getItemMinQuantity() {
        return itemMinQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_min_quantity
     *
     * @param itemMinQuantity the value for pos_item.item_min_quantity
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemMinQuantity(BigDecimal itemMinQuantity) {
        this.itemMinQuantity = itemMinQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_wholesale_gross2
     *
     * @return the value of pos_item.item_wholesale_gross2
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public BigDecimal getItemWholesaleGross2() {
        return itemWholesaleGross2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_wholesale_gross2
     *
     * @param itemWholesaleGross2 the value for pos_item.item_wholesale_gross2
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemWholesaleGross2(BigDecimal itemWholesaleGross2) {
        this.itemWholesaleGross2 = itemWholesaleGross2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_wholesale_fixed_gross2
     *
     * @return the value of pos_item.item_wholesale_fixed_gross2
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public Byte getItemWholesaleFixedGross2() {
        return itemWholesaleFixedGross2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_wholesale_fixed_gross2
     *
     * @param itemWholesaleFixedGross2 the value for pos_item.item_wholesale_fixed_gross2
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemWholesaleFixedGross2(Byte itemWholesaleFixedGross2) {
        this.itemWholesaleFixedGross2 = itemWholesaleFixedGross2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_wholesale_gross3
     *
     * @return the value of pos_item.item_wholesale_gross3
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public BigDecimal getItemWholesaleGross3() {
        return itemWholesaleGross3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_wholesale_gross3
     *
     * @param itemWholesaleGross3 the value for pos_item.item_wholesale_gross3
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemWholesaleGross3(BigDecimal itemWholesaleGross3) {
        this.itemWholesaleGross3 = itemWholesaleGross3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_wholesale_fixed_gross3
     *
     * @return the value of pos_item.item_wholesale_fixed_gross3
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public Byte getItemWholesaleFixedGross3() {
        return itemWholesaleFixedGross3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_wholesale_fixed_gross3
     *
     * @param itemWholesaleFixedGross3 the value for pos_item.item_wholesale_fixed_gross3
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemWholesaleFixedGross3(Byte itemWholesaleFixedGross3) {
        this.itemWholesaleFixedGross3 = itemWholesaleFixedGross3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_wholesale_gross4
     *
     * @return the value of pos_item.item_wholesale_gross4
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public BigDecimal getItemWholesaleGross4() {
        return itemWholesaleGross4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_wholesale_gross4
     *
     * @param itemWholesaleGross4 the value for pos_item.item_wholesale_gross4
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemWholesaleGross4(BigDecimal itemWholesaleGross4) {
        this.itemWholesaleGross4 = itemWholesaleGross4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_wholesale_fixed_gross4
     *
     * @return the value of pos_item.item_wholesale_fixed_gross4
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public Byte getItemWholesaleFixedGross4() {
        return itemWholesaleFixedGross4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_wholesale_fixed_gross4
     *
     * @param itemWholesaleFixedGross4 the value for pos_item.item_wholesale_fixed_gross4
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemWholesaleFixedGross4(Byte itemWholesaleFixedGross4) {
        this.itemWholesaleFixedGross4 = itemWholesaleFixedGross4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_max_price
     *
     * @return the value of pos_item.item_max_price
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public BigDecimal getItemMaxPrice() {
        return itemMaxPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_max_price
     *
     * @param itemMaxPrice the value for pos_item.item_max_price
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemMaxPrice(BigDecimal itemMaxPrice) {
        this.itemMaxPrice = itemMaxPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_transfer_day
     *
     * @return the value of pos_item.item_transfer_day
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public Integer getItemTransferDay() {
        return itemTransferDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_transfer_day
     *
     * @param itemTransferDay the value for pos_item.item_transfer_day
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemTransferDay(Integer itemTransferDay) {
        this.itemTransferDay = itemTransferDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_in_tax
     *
     * @return the value of pos_item.item_in_tax
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public BigDecimal getItemInTax() {
        return itemInTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_in_tax
     *
     * @param itemInTax the value for pos_item.item_in_tax
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemInTax(BigDecimal itemInTax) {
        this.itemInTax = itemInTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_out_tax
     *
     * @return the value of pos_item.item_out_tax
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public BigDecimal getItemOutTax() {
        return itemOutTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_out_tax
     *
     * @param itemOutTax the value for pos_item.item_out_tax
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemOutTax(BigDecimal itemOutTax) {
        this.itemOutTax = itemOutTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_manufacture_flag
     *
     * @return the value of pos_item.item_manufacture_flag
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public Byte getItemManufactureFlag() {
        return itemManufactureFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_manufacture_flag
     *
     * @param itemManufactureFlag the value for pos_item.item_manufacture_flag
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemManufactureFlag(Byte itemManufactureFlag) {
        this.itemManufactureFlag = itemManufactureFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_finished_rate
     *
     * @return the value of pos_item.item_finished_rate
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public BigDecimal getItemFinishedRate() {
        return itemFinishedRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_finished_rate
     *
     * @param itemFinishedRate the value for pos_item.item_finished_rate
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemFinishedRate(BigDecimal itemFinishedRate) {
        this.itemFinishedRate = itemFinishedRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_extend1
     *
     * @return the value of pos_item.item_extend1
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public String getItemExtend1() {
        return itemExtend1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_extend1
     *
     * @param itemExtend1 the value for pos_item.item_extend1
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemExtend1(String itemExtend1) {
        this.itemExtend1 = itemExtend1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_extend2
     *
     * @return the value of pos_item.item_extend2
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public String getItemExtend2() {
        return itemExtend2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_extend2
     *
     * @param itemExtend2 the value for pos_item.item_extend2
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemExtend2(String itemExtend2) {
        this.itemExtend2 = itemExtend2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_extend3
     *
     * @return the value of pos_item.item_extend3
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public String getItemExtend3() {
        return itemExtend3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_extend3
     *
     * @param itemExtend3 the value for pos_item.item_extend3
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemExtend3(String itemExtend3) {
        this.itemExtend3 = itemExtend3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_has_matrix
     *
     * @return the value of pos_item.item_has_matrix
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public Byte getItemHasMatrix() {
        return itemHasMatrix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_has_matrix
     *
     * @param itemHasMatrix the value for pos_item.item_has_matrix
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemHasMatrix(Byte itemHasMatrix) {
        this.itemHasMatrix = itemHasMatrix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_creator
     *
     * @return the value of pos_item.item_creator
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public String getItemCreator() {
        return itemCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_creator
     *
     * @param itemCreator the value for pos_item.item_creator
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemCreator(String itemCreator) {
        this.itemCreator = itemCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_transfer_fix_type
     *
     * @return the value of pos_item.item_transfer_fix_type
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public Integer getItemTransferFixType() {
        return itemTransferFixType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_transfer_fix_type
     *
     * @param itemTransferFixType the value for pos_item.item_transfer_fix_type
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemTransferFixType(Integer itemTransferFixType) {
        this.itemTransferFixType = itemTransferFixType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.item_wholesale_fix_type
     *
     * @return the value of pos_item.item_wholesale_fix_type
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public Integer getItemWholesaleFixType() {
        return itemWholesaleFixType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.item_wholesale_fix_type
     *
     * @param itemWholesaleFixType the value for pos_item.item_wholesale_fix_type
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setItemWholesaleFixType(Integer itemWholesaleFixType) {
        this.itemWholesaleFixType = itemWholesaleFixType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.branch_num
     *
     * @return the value of pos_item.branch_num
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public Integer getBranchNum() {
        return branchNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.branch_num
     *
     * @param branchNum the value for pos_item.branch_num
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setBranchNum(Integer branchNum) {
        this.branchNum = branchNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_item.aged_timestamp
     *
     * @return the value of pos_item.aged_timestamp
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public Date getAgedTimestamp() {
        return agedTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_item.aged_timestamp
     *
     * @param agedTimestamp the value for pos_item.aged_timestamp
     *
     * @mbggenerated Mon Jun 01 22:38:21 CST 2020
     */
    public void setAgedTimestamp(Date agedTimestamp) {
        this.agedTimestamp = agedTimestamp;
    }
}